steps:
  - name: "python:3.9"
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "pip"]
  - name: "python:3.9"
    entrypoint: python
    args: ["-m", "pip", "install", "setuptools", "wheel", "twine", "yolk3k", "--user"]
  - name: "python:3.9"
    id: "BUILD WHEEL"
    entrypoint: "python"
    args: ["setup.py", "sdist", "bdist_wheel"]
    waitFor: ["-"]
artifacts:
  python_packages:
    - repository: $_REPOSITORY
      paths: ["dist/*"]
